name: Build and Test

on:
  push:
    branches-ignore:
      - "master"

jobs:
  buildAndTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 10.15.3

      - name: Cache node_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node_modules-

      - name: Install dependencies
        run: npm install
        env:
          CYPRESS_INSTALL_BINARY: 0

      - name: Build app
        run: npm run build

      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          start: npm start
          record: true

        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
